name: Check TestCi in PR

on:
  pull_request:
    types: labeled

jobs:  
  exec-tests:
    uses: ./.github/workflows/reusable-test-suite.yml
    if: github.event.label.name == 'exec-CI'
   
  remove-label-from-pr:
    runs-on: ubuntu-latest
    needs: [exec-tests]
    if: always() && github.event.label.name == 'exec-CI'
    permissions:
      pull-requests: write
    steps:
      - name: 'Code checkout'
        uses: actions/checkout@v4
      - name: 'remove label'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ${{ env.LABEL_TO_CHECK }}
